import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import { Layout } from '@/components/Layout';
import AntdStyledComponentsRegistry from '@/components/AntdStyledComponentsRegistry';

import './globals.css';

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['cyrillic'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Chrono Planner',
  description: 'Generated by Ovsepyan',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={roboto.className} suppressHydrationWarning={true}>
        <AntdStyledComponentsRegistry>
          <Layout>{children}</Layout>
        </AntdStyledComponentsRegistry>
      </body>
    </html>
  );
}
